
//! Autogenerated weights for `pallet_medical_history_reader`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-02-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ICCSW-045521-NB`, CPU: `Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/healthchain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_medical_history_reader
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --output
// ./pallets/medical-history-reader/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_medical_history_reader`.
pub struct WeightInfo<T>(PhantomData<T>);
//impl<T: frame_system::Config> pallet_medical_history_reader::WeightInfo for WeightInfo<T> {  linha substituída após a geração desse arquivo.
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `MedicalHistory::PatientRecords` (r:1 w:0)
	/// Proof: `MedicalHistory::PatientRecords` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	fn read_own_data() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `270`
		//  Estimated: `3701`
		// Minimum execution time: 23_638_000 picoseconds.
		Weight::from_parts(24_024_000, 0)
			.saturating_add(Weight::from_parts(0, 3701))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `MedicalPermissions::Permissions` (r:1 w:0)
	/// Proof: `MedicalPermissions::Permissions` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `MedicalHistory::PatientRecords` (r:1 w:0)
	/// Proof: `MedicalHistory::PatientRecords` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	fn read_patient_data() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `397`
		//  Estimated: `3701`
		// Minimum execution time: 32_935_000 picoseconds.
		Weight::from_parts(33_427_000, 0)
			.saturating_add(Weight::from_parts(0, 3701))
			.saturating_add(T::DbWeight::get().reads(2))
	}
}
