
//! Autogenerated weights for `pallet_template`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-01-06, STEPS: `50`, REPEAT: `200`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `CAF-038841NB.local.inatel.br`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/healthchain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_template
// --extrinsic=*
// --steps=50
// --repeat=200
// --wasm-execution=compiled
// --output=pallets/template/src/weights.rs
// --template=.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_medical_history_reader.
pub trait WeightInfo {
    fn read_own_data() -> Weight;
    fn read_patient_data() -> Weight;
}

/// Weights for pallet_medical_history_reader using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn read_own_data() -> Weight {
        // Custo fixo baixo (10_000) + 1 Leitura no Banco de Dados (reads(1))
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(1_u64))
    }

    fn read_patient_data() -> Weight {
        // Custo fixo baixo (10_000) + 1 Leitura no Banco de Dados (reads(1))
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(1_u64))
    }
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    fn read_own_data() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
    }

    fn read_patient_data() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
    }
}